-- Factory (production) database schema

CREATE TABLE IF NOT EXISTS lines (
  line_id  TEXT PRIMARY KEY,
  name     TEXT NOT NULL,
  location TEXT
);

CREATE TABLE IF NOT EXISTS machines (
  machine_id TEXT PRIMARY KEY,
  line_id    TEXT REFERENCES lines (line_id),
  station    TEXT NOT NULL,
  model      TEXT
);

CREATE TABLE IF NOT EXISTS production_events (
  event_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id      TEXT NOT NULL,
  work_order_id TEXT,                          -- NULL, joined via batch_id (App API mapping)
  line_id       TEXT,
  station       TEXT NOT NULL
                  CHECK (station IN ('SORTING', 'WASHING', 'DRYING', 'FOLDING', 'DISPATCH')),
  event_type    TEXT NOT NULL,
  quantity      INTEGER,
  event_time    TIMESTAMPTZ NOT NULL,         
  recorded_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  machine_id    TEXT,
  operator      TEXT,
  status        TEXT NOT NULL DEFAULT 'RECORDED',
  notes         TEXT
);

CREATE INDEX IF NOT EXISTS idx_production_events_batch   ON production_events (batch_id);
CREATE INDEX IF NOT EXISTS idx_production_events_station ON production_events (station);

-- the collector connect with a read only role
GRANT CONNECT ON DATABASE :"factory_db" TO :"ro_user";
GRANT USAGE ON SCHEMA public TO :"ro_user";
GRANT SELECT ON ALL TABLES IN SCHEMA public TO :"ro_user";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO :"ro_user";
